[settings]
DEBUG=true
ALLOWED_HOSTS=['*']

[starmap]
HOURS="18"
MINUTES="20"
WIDTH="1500"
HEIGHT="1500"
ANGLE="180"
STARMAP_FILENAME="sky_view.svg"

[smtp]
EMAIL_HOST="smtp.yandex.ru"
EMAIL_PORT="465"
EMAIL_USE_TLS=false
EMAIL_USE_SSL=true
